# Generated by Django 5.0 on 2024-01-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='emai',
            new_name='email',
        ),
    ]
