# Generated by Django 5.0 on 2024-01-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_rename_emai_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default=datetime.datetime(2024, 1, 7, 12, 4, 13, 996757, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
    ]
