# Generated by Django 5.0 on 2024-01-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_skills_jobpost_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default='Full Time', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='desc',
            field=models.TextField(),
        ),
    ]
